node: The chown_paths may be too large to chown
Aiven-Open/astacus pull request #132
Opened 2023-08-14 22:33 UTC by RommelLayco

The number of files to chown could be really large such that the argument list becomes to long.

2023-08-14 22:37 UTC, reedwade commented on astacus/node/download.py
> +                    *sorted(chowned_path),
Probly need to drop the `sorted()`

2023-08-14 23:04 UTC, kmichel-aiven commented on astacus/node/download.py
>                  # We're very specific to allow a sufficiently restrictive sudoers configuration
If the list is very long, we probably don't want to spawn thousand of subprocesses,
one for every single file, a chunked approach might be better:

```python
                # We're very specific to allow a sufficiently restrictive sudoers configuration
                chunk_size = 1000
                sorted_paths = sorted(chowned_paths)
                for chunk_start in range(0, len(sorted_paths), chunk_size):
                    cmd: Sequence[str | Path] = [
                        "/usr/bin/sudo",
                        "/usr/bin/chown",
                        f"--from={astacus_user}:{dst_owner_gid}",
                        f"{dst_owner_uid}",
                        "--",
                        *sorted_paths[chunk_start: chunk_start + chunk_size],
                    ]
                    subprocess.run(cmd, shell=False, check=True, cwd=self.dst)
```

2023-08-18 06:08 UTC, kmichel-aiven requested changes
Formatting issue found by CI.

2023-08-21 06:41 UTC, kmichel-aiven approved these changes

2023-08-21 06:41 UTC, merged