tests: add typing
Aiven-Open/astacus pull request #171
Opened 2023-12-11 12:59 UTC by joelynch

Been having some trouble reading tests without type annotations.

* add missing types to test methods
* remove unused fixtures `fixture_utils_http_request_list`
* just use `Mock` instead of `SimpleNamespace`, it is better for typing (mypy understands that `Mock` is a subtype / supertype of every type similar to `Any`).

2023-12-12 18:12 UTC, kmichel-aiven requested changes

2023-12-12 18:12 UTC, kmichel-aiven commented on tests/unit/coordinator/plugins/cassandra/test_plugin.py
>      assert result is None
The test disables the static check for "returns None" and then assert that the return is None.
I think we can just remove the assert and the ignore.

2023-12-12 18:12 UTC, kmichel-aiven commented on tests/unit/coordinator/plugins/cassandra/test_plugin.py
> +    context = Mock()
cluster and context are super easy to create, no need to take risks and use mocks.

```python
cluster = Cluster(nodes=[])
context = StepsContext()
```

(same in other tests in the same file).

2023-12-12 18:12 UTC, kmichel-aiven commented on tests/unit/coordinator/plugins/cassandra/test_plugin.py
>          assert result is None
Here too, we can just let mypy check the return type.

2023-12-12 18:12 UTC, kmichel-aiven commented on tests/unit/coordinator/plugins/cassandra/test_restore_steps.py
> +    result = await step.run_step(cluster, context)  # type: ignore[func-returns-value]
Same as the other test files, no need to use mocks and dynamically test static types.

2023-12-12 18:12 UTC, kmichel-aiven commented on tests/unit/coordinator/test_cleanup.py
> +):
`-> None`

2023-12-12 18:12 UTC, kmichel-aiven commented on tests/unit/coordinator/test_cleanup.py
> +def test_api_cleanup_flow(fail_at: int | None, client: TestClient, populated_mstorage: MultiRohmuStorage, app: FastAPI):
`-> None`

2023-12-12 18:12 UTC, kmichel-aiven commented on tests/unit/coordinator/test_cleanup.py
> +):
`-> None`

2023-12-12 18:12 UTC, kmichel-aiven commented on tests/unit/coordinator/test_restore.py
> +):
`-> None`

2023-12-12 18:12 UTC, kmichel-aiven commented on tests/unit/node/test_node_cassandra.py
> +    def __init__(self, *, app, client, mocker, tmpdir: py.path.local):
`-> None`

2023-12-12 18:12 UTC, kmichel-aiven commented on tests/unit/node/test_node_cassandra.py
> +def test_api_cassandra_subop(app: FastAPI, ctenv: CassandraTestEnv, mocker: MockerFixture, subop: ipc.CassandraSubOp):
`-> None`

2023-12-12 18:12 UTC, kmichel-aiven commented on tests/unit/node/test_node_cassandra.py
> +):
`-> None`

2023-12-13 09:46 UTC, joelynch commented on astacus/common/rohmustorage.py
> +    def get_storage(self, name: str | None) -> RohmuStorage:
Hmm are you sure about this?  I think the type widening makes sense in this case, it is matching the type of `RohmuStorage.__init__` which this method just forwards to.

2023-12-13 09:50 UTC, joelynch commented on tests/unit/common/test_op.py
> +class MockOp(op.Op):
Good point, I can just use Op directly

2023-12-13 09:55 UTC, joelynch commented on tests/unit/common/test_utils.py
> +    assert not Path(f3_path).exists()  # type: ignore[unreachable]
I'll change the exception type, but also this is a mypy bug in this version of mypy.  It does not work well with `pytest.raises`.  I've added a comment.

2023-12-15 08:58 UTC, kmichel-aiven approved these changes

2023-12-15 08:58 UTC, kmichel-aiven commented on tests/unit/common/test_utils.py
> +    assert not Path(f3_path).exists()  # type: ignore[unreachable]
I'd change this to a plain try/except/else (with the not exist in the except branch and an assert False in the else branch), that wouldn't require mypy to know about pytest special things.

2023-12-15 08:59 UTC, merged